name:                batchnorm
version:             0.0.0
license:             BSD3
tested-with:         GHC >= 8.2

extra-source-files:
- README.md

synopsis:            ...
category:            ML

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: See README.md

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wredundant-constraints
# - -O0
# - -fprint-explicit-kinds
dependencies:
- base >=4.7 && <5
- backprop >= 0.2.5
- binary
- bytestring
- conduit
- containers
- deepseq
- finite-typelits
- foldl >= 1.4
- ghc-typelits-extra
- ghc-typelits-knownnat
- ghc-typelits-natnormalise
- hmatrix
- hmatrix-backprop >= 0.1.2.2
- hmatrix-vector-sized
- microlens
- microlens-th
- mwc-random
- one-liner
- one-liner-instances
- opto
- primitive
- profunctors
- statistics
- transformers
- type-combinators
- typelits-witnesses
- vector
- vector-sized

library:
  source-dirs: src

executables:
  mnist:
    main: batchnorm.hs
    dependencies:
    - batchnorm
    - data-default
    - filepath
    - mnist-idx
    - time

    - hmatrix
    - mnist-idx
    - mwc-random
    - one-liner-instances
    - split
  NN2:
    main: NN2.hs
    dependencies:
    - batchnorm
    - data-default
    - filepath
    - mnist-idx
    - random
    - split
    - time
